# Site
name: "kooks7"
title: "kooks7"
description: "kooks7의 기술블로그!"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
google_analytics: "UA-xxxxxxxx-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: busanminjae@gmail.com

# Authors
authors:
  kooks7:
    name: kooks7
    display_name: kooks7
    avatar: "assets/images/me.png"
    gravatar:
    email: busanminjae@gmail.com
    web: https://kooks7.github.io
    twitter: https://twitter.com
    instagram: https://www.instagram.com/kooks7
    description: "안녕하세요. 백앤드 개발자 김민재입니다."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 10
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"


highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
  exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
