title: Kooks7
description: -Everthing is here

url: http://kooks7.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

collections:
- kooks7_collection

collections_dir: kooks7_collections

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 7

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: kooks7
  twitter: 
  facebook: minjae.kim.77985741
  email: busanminjae@gmail.com

google_analytics: "UA-58263416-1"
